/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat.pb-c.h"
void   chat__user_registration__init
                     (Chat__UserRegistration         *message)
{
  static const Chat__UserRegistration init_value = CHAT__USER_REGISTRATION__INIT;
  *message = init_value;
}
size_t chat__user_registration__get_packed_size
                     (const Chat__UserRegistration *message)
{
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__user_registration__pack
                     (const Chat__UserRegistration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__user_registration__pack_to_buffer
                     (const Chat__UserRegistration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__UserRegistration *
       chat__user_registration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__UserRegistration *)
     protobuf_c_message_unpack (&chat__user_registration__descriptor,
                                allocator, len, data);
}
void   chat__user_registration__free_unpacked
                     (Chat__UserRegistration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__user_info__init
                     (Chat__UserInfo         *message)
{
  static const Chat__UserInfo init_value = CHAT__USER_INFO__INIT;
  *message = init_value;
}
size_t chat__user_info__get_packed_size
                     (const Chat__UserInfo *message)
{
  assert(message->base.descriptor == &chat__user_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__user_info__pack
                     (const Chat__UserInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__user_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__user_info__pack_to_buffer
                     (const Chat__UserInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__user_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__UserInfo *
       chat__user_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__UserInfo *)
     protobuf_c_message_unpack (&chat__user_info__descriptor,
                                allocator, len, data);
}
void   chat__user_info__free_unpacked
                     (Chat__UserInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__user_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__user_request__init
                     (Chat__UserRequest         *message)
{
  static const Chat__UserRequest init_value = CHAT__USER_REQUEST__INIT;
  *message = init_value;
}
size_t chat__user_request__get_packed_size
                     (const Chat__UserRequest *message)
{
  assert(message->base.descriptor == &chat__user_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__user_request__pack
                     (const Chat__UserRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__user_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__user_request__pack_to_buffer
                     (const Chat__UserRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__user_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__UserRequest *
       chat__user_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__UserRequest *)
     protobuf_c_message_unpack (&chat__user_request__descriptor,
                                allocator, len, data);
}
void   chat__user_request__free_unpacked
                     (Chat__UserRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__user_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__connected_users_response__init
                     (Chat__ConnectedUsersResponse         *message)
{
  static const Chat__ConnectedUsersResponse init_value = CHAT__CONNECTED_USERS_RESPONSE__INIT;
  *message = init_value;
}
size_t chat__connected_users_response__get_packed_size
                     (const Chat__ConnectedUsersResponse *message)
{
  assert(message->base.descriptor == &chat__connected_users_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__connected_users_response__pack
                     (const Chat__ConnectedUsersResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__connected_users_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__connected_users_response__pack_to_buffer
                     (const Chat__ConnectedUsersResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__connected_users_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ConnectedUsersResponse *
       chat__connected_users_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ConnectedUsersResponse *)
     protobuf_c_message_unpack (&chat__connected_users_response__descriptor,
                                allocator, len, data);
}
void   chat__connected_users_response__free_unpacked
                     (Chat__ConnectedUsersResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__connected_users_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__change_status__init
                     (Chat__ChangeStatus         *message)
{
  static const Chat__ChangeStatus init_value = CHAT__CHANGE_STATUS__INIT;
  *message = init_value;
}
size_t chat__change_status__get_packed_size
                     (const Chat__ChangeStatus *message)
{
  assert(message->base.descriptor == &chat__change_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__change_status__pack
                     (const Chat__ChangeStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__change_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__change_status__pack_to_buffer
                     (const Chat__ChangeStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__change_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ChangeStatus *
       chat__change_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ChangeStatus *)
     protobuf_c_message_unpack (&chat__change_status__descriptor,
                                allocator, len, data);
}
void   chat__change_status__free_unpacked
                     (Chat__ChangeStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__change_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__message_communication__init
                     (Chat__MessageCommunication         *message)
{
  static const Chat__MessageCommunication init_value = CHAT__MESSAGE_COMMUNICATION__INIT;
  *message = init_value;
}
size_t chat__message_communication__get_packed_size
                     (const Chat__MessageCommunication *message)
{
  assert(message->base.descriptor == &chat__message_communication__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__message_communication__pack
                     (const Chat__MessageCommunication *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__message_communication__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__message_communication__pack_to_buffer
                     (const Chat__MessageCommunication *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__message_communication__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__MessageCommunication *
       chat__message_communication__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__MessageCommunication *)
     protobuf_c_message_unpack (&chat__message_communication__descriptor,
                                allocator, len, data);
}
void   chat__message_communication__free_unpacked
                     (Chat__MessageCommunication *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__message_communication__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__client_petition__init
                     (Chat__ClientPetition         *message)
{
  static const Chat__ClientPetition init_value = CHAT__CLIENT_PETITION__INIT;
  *message = init_value;
}
size_t chat__client_petition__get_packed_size
                     (const Chat__ClientPetition *message)
{
  assert(message->base.descriptor == &chat__client_petition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__client_petition__pack
                     (const Chat__ClientPetition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__client_petition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__client_petition__pack_to_buffer
                     (const Chat__ClientPetition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__client_petition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ClientPetition *
       chat__client_petition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ClientPetition *)
     protobuf_c_message_unpack (&chat__client_petition__descriptor,
                                allocator, len, data);
}
void   chat__client_petition__free_unpacked
                     (Chat__ClientPetition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__client_petition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__server_response__init
                     (Chat__ServerResponse         *message)
{
  static const Chat__ServerResponse init_value = CHAT__SERVER_RESPONSE__INIT;
  *message = init_value;
}
size_t chat__server_response__get_packed_size
                     (const Chat__ServerResponse *message)
{
  assert(message->base.descriptor == &chat__server_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__server_response__pack
                     (const Chat__ServerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__server_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__server_response__pack_to_buffer
                     (const Chat__ServerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__server_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ServerResponse *
       chat__server_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ServerResponse *)
     protobuf_c_message_unpack (&chat__server_response__descriptor,
                                allocator, len, data);
}
void   chat__server_response__free_unpacked
                     (Chat__ServerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__server_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat__user_registration__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserRegistration, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserRegistration, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__user_registration__field_indices_by_name[] = {
  1,   /* field[1] = ip */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange chat__user_registration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat__user_registration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.UserRegistration",
  "UserRegistration",
  "Chat__UserRegistration",
  "chat",
  sizeof(Chat__UserRegistration),
  2,
  chat__user_registration__field_descriptors,
  chat__user_registration__field_indices_by_name,
  1,  chat__user_registration__number_ranges,
  (ProtobufCMessageInit) chat__user_registration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__user_info__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserInfo, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserInfo, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserInfo, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__user_info__field_indices_by_name[] = {
  2,   /* field[2] = ip */
  1,   /* field[1] = status */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange chat__user_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chat__user_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.UserInfo",
  "UserInfo",
  "Chat__UserInfo",
  "chat",
  sizeof(Chat__UserInfo),
  3,
  chat__user_info__field_descriptors,
  chat__user_info__field_indices_by_name,
  1,  chat__user_info__number_ranges,
  (ProtobufCMessageInit) chat__user_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__user_request__field_descriptors[1] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserRequest, user),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__user_request__field_indices_by_name[] = {
  0,   /* field[0] = user */
};
static const ProtobufCIntRange chat__user_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chat__user_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.UserRequest",
  "UserRequest",
  "Chat__UserRequest",
  "chat",
  sizeof(Chat__UserRequest),
  1,
  chat__user_request__field_descriptors,
  chat__user_request__field_indices_by_name,
  1,  chat__user_request__number_ranges,
  (ProtobufCMessageInit) chat__user_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__connected_users_response__field_descriptors[1] =
{
  {
    "connectedUsers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Chat__ConnectedUsersResponse, n_connectedusers),
    offsetof(Chat__ConnectedUsersResponse, connectedusers),
    &chat__user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__connected_users_response__field_indices_by_name[] = {
  0,   /* field[0] = connectedUsers */
};
static const ProtobufCIntRange chat__connected_users_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chat__connected_users_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ConnectedUsersResponse",
  "ConnectedUsersResponse",
  "Chat__ConnectedUsersResponse",
  "chat",
  sizeof(Chat__ConnectedUsersResponse),
  1,
  chat__connected_users_response__field_descriptors,
  chat__connected_users_response__field_indices_by_name,
  1,  chat__connected_users_response__number_ranges,
  (ProtobufCMessageInit) chat__connected_users_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__change_status__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__ChangeStatus, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__ChangeStatus, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__change_status__field_indices_by_name[] = {
  1,   /* field[1] = status */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange chat__change_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat__change_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ChangeStatus",
  "ChangeStatus",
  "Chat__ChangeStatus",
  "chat",
  sizeof(Chat__ChangeStatus),
  2,
  chat__change_status__field_descriptors,
  chat__change_status__field_indices_by_name,
  1,  chat__change_status__number_ranges,
  (ProtobufCMessageInit) chat__change_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__message_communication__field_descriptors[3] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__MessageCommunication, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recipient",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__MessageCommunication, recipient),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__MessageCommunication, sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__message_communication__field_indices_by_name[] = {
  0,   /* field[0] = message */
  1,   /* field[1] = recipient */
  2,   /* field[2] = sender */
};
static const ProtobufCIntRange chat__message_communication__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chat__message_communication__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.MessageCommunication",
  "MessageCommunication",
  "Chat__MessageCommunication",
  "chat",
  sizeof(Chat__MessageCommunication),
  3,
  chat__message_communication__field_descriptors,
  chat__message_communication__field_indices_by_name,
  1,  chat__message_communication__number_ranges,
  (ProtobufCMessageInit) chat__message_communication__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__client_petition__field_descriptors[5] =
{
  {
    "option",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientPetition, option),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "registration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientPetition, registration),
    &chat__user_registration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "users",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientPetition, users),
    &chat__user_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "change",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientPetition, change),
    &chat__change_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageCommunication",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientPetition, messagecommunication),
    &chat__message_communication__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__client_petition__field_indices_by_name[] = {
  3,   /* field[3] = change */
  4,   /* field[4] = messageCommunication */
  0,   /* field[0] = option */
  1,   /* field[1] = registration */
  2,   /* field[2] = users */
};
static const ProtobufCIntRange chat__client_petition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor chat__client_petition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ClientPetition",
  "ClientPetition",
  "Chat__ClientPetition",
  "chat",
  sizeof(Chat__ClientPetition),
  5,
  chat__client_petition__field_descriptors,
  chat__client_petition__field_indices_by_name,
  1,  chat__client_petition__number_ranges,
  (ProtobufCMessageInit) chat__client_petition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__server_response__field_descriptors[7] =
{
  {
    "option",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, option),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverMessage",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, servermessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectedUsers",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, connectedusers),
    &chat__connected_users_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageCommunication",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, messagecommunication),
    &chat__message_communication__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userInfoResponse",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, userinforesponse),
    &chat__user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "change",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, change),
    &chat__change_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__server_response__field_indices_by_name[] = {
  6,   /* field[6] = change */
  1,   /* field[1] = code */
  3,   /* field[3] = connectedUsers */
  4,   /* field[4] = messageCommunication */
  0,   /* field[0] = option */
  2,   /* field[2] = serverMessage */
  5,   /* field[5] = userInfoResponse */
};
static const ProtobufCIntRange chat__server_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor chat__server_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ServerResponse",
  "ServerResponse",
  "Chat__ServerResponse",
  "chat",
  sizeof(Chat__ServerResponse),
  7,
  chat__server_response__field_descriptors,
  chat__server_response__field_indices_by_name,
  1,  chat__server_response__number_ranges,
  (ProtobufCMessageInit) chat__server_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
